#!/bin/sh

version: "3"

#SCRIPT
services:
  web:
    build: ./frontend
    depends_on:
      - api
    ports:
      - "8888:80"
    networks:
     -back
 
#API 
  api:
    build: ./backend
    depends_on:
      - mongo
    ports:
      - "8000:8080"
    networks: 
     -back

#DATABASE  
  mongo:
    image: mongo
    restart: always
    volumes: 
      - mongodb:/data/db
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: tanguy
      MONGODB_INITDB_ROOT_PASSWORD: tanguy
      
      
    networks: 
     -back

networks:
  -back:

volumes: 
  mongodb:
