version: "3"

#SCRIPT
services:
  web:
    build: ./frontend
    depends_on:
      - api
    ports:
      - 3000:3000
    networks:
     - back
 
#API 
  api:
    build: ./backend
    depends_on:
      - mongo
    ports:
      - 8080:8080
    networks: 
     - back

#DATABASE  
  mongo:
    image: mongo
    restart: always
    volumes: 
      - mongodb:/data/db
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: tanguy
      MONGODB_INITDB_ROOT_PASSWORD: tanguy
      
      
    networks: 
     - back


networks:
  - back:

volumes: 
  mongodb:
