version: "3"
services:


  web:
    build: ./frontend
    depends_on:
      - api
    ports:
      - 3000:3000
    networks:
      - back


  api:
    build: ./backend
    depends_on:
      - mongo
    ports:
      - 8080:8080
    networks: 
     - back


  mongo:
    image: mongo
    restart: always
    volumes: 
      - mongo:/data/mongo
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: tanguy
      MONGODB_INITDB_ROOT_PASSWORD: tanguy

    networks: 
     - back

networks:
  back:

volumes: 
  mongo: