#!/bin/sh

version: "3"

#SCRIPT
services:
  web:
    build: ./frontend
    depends_on:
      - api
    ports:
      - "8888:80"
    networks:
      - network-backend
 
#API 
  api:
    build: ./backend
    depends_on:
      - mongo
    ports:
      - "8001:80"
    networks: 
     - network-backend

#DATABASE  
  mongo:
    image: mongo
    restart: always
    volumes: 
      - mongodb_data:/data/db
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: tanguy
      MONGODB_INITDB_ROOT_PASSWORD: tanguy
    ports:
       - "8000:80"
    networks: 
     - network-backend

networks:
  network-backend:

volumes: 
  mongodb_data:
